---
- hosts: 172.31.36.143
  become: yes
  tasks:
  - name: I want to execute linux commands
    command: hostname -f
    register: myResult

  - name: I want to display task myResult
    debug:
        msg: "{{myResult}}"

  - name: I want to install git
    apt:
     name: git
     state: present
    when: myResult.stderr ==""

  - name: I want to install  tree
    apt:
     name: tree
     state: present
    when: myResult.stderr !=""
