---

- hosts: 172.31.36.143
  become: yes
  tasks:
  - include_tasks: myFile.yml
  - name: I want to install webserver
    apt:
      name: apache2
      state: absent
  
  - name: I want to copy file to ansible nodes
    template:
        src: myIndex.j2
        dest: /var/www/html/index.html
