---
- hosts: 172.31.36.143
  tasks: 
  - name: Install tree in ansible
    apt:
      name: tree
      state: present
    tags: myTree

  - name: Install wget
    apt:
      name: wget
      stateeeee: present
    tags: myWget
    ignore_errors: yes

  - name: Install git
    apt:
      name: git
      state: present
    tags: mygit
    