---
- hosts: all
  become: yes
  tasks:
  - name: want to install web server on ansible nodes
    apt:
      name: apache2
      state: present
  
  - name: I want to start webserver on ansible
    service:
       name: apache2
       state: started

  - name: I want to install wget
    apt:
      name:  wget
      state: present