---
- hosts: myWebservers
  become: yes
  tasks:
  - name: want to install web server on ansible nodes
    apt:
      name: "{{myWebpackforUbuntu}}"
      state: present
    when: ansible_os_family== "Debian"
  
  - name: I want to start webserver on ansible
    service:
       name: "{{myWebpackforUbuntu}}"
       state: started
    when: ansible_os_family== "Debian"

  - name: I want to install webserver on ansible node Redhat
    yum:
       name: "{{myWebpackforRedHat}}"
       state: present
    when: ansible_os_family== "RedHat"

  - name: I want to start webserver on ansible node RedHat
    service:
       name: "{{myWebpackforRedHat}}"
       state: started
    when: ansible_os_family== "RedHat"